apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: popular-slides

build:
  artifacts:
    - image: timebertt/refuel-web-app
      context: userInterface
    - image: timebertt/popular-slides-spark
      context: spark-app
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
