apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: refuel

build:
  artifacts:
  - image: timebertt/refuel-web-app
    context: web-app
  - image: timebertt/refuel-spark-app
    context: spark-app
  local:
    useBuildkit: true

deploy:
  kustomize:
    paths:
    - k8s/base

profiles:
- name: local
- name: gardener-shoot
  deploy:
    kustomize:
      paths:
      - k8s/overlays/gardener-shoot
