apiVersion: apps/v1
kind: Deployment
metadata:
  name: popular-slides-spark
  labels:
    app: popular-slides-spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popular-slides-spark
  template:
    metadata:
      labels:
        app: popular-slides-spark
    spec:
      containers:
      - name: popular-slides-spark
        image: timebertt/popular-slides-spark
        env:
        - name: HADOOP_CONF_DIR
          value: "/hadoop-config"
        - name: HADOOP_USER_NAME
          value: "root"
        - name: HADOOP_JAAS_DEBUG
          value: "true"
        volumeMounts:
        - name: hadoop-conf
          mountPath: /hadoop-config
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
