apiVersion: apps/v1
kind: Deployment
metadata:
  name: popular-slides-spark
  labels:
    app: popular-slides-spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popular-slides-spark
  template:
    metadata:
      labels:
        app: popular-slides-spark
    spec:
#      serviceAccountName: spark-app # needed when submitting jobs to kubernetes
      containers:
      - name: popular-slides-spark
        image: timebertt/popular-slides-spark
        args:
#        - --conf
#        - spark.kubernetes.container.image=bitnami/spark:3.0.0
        - --conf
        - spark.executor.cores=2
        - --conf
        - spark.executor.memory=4000m
        - /app/spark-app.py
        env:
        - name: HADOOP_CONF_DIR
          value: "/hadoop-config"
        - name: HADOOP_USER_NAME
          value: "root"
        - name: HADOOP_JAAS_DEBUG
          value: "true"
#        - name: MASTER
#          value: "local"
        - name: MASTER
          value: "yarn"
#        - name: MASTER
#          value: "k8s://https://kubernetes.default:443"
        - name: DEPLOY_MODE
          value: "client"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: hadoop-conf
          mountPath: /hadoop-config
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
