#Begin: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: refuel-web-app
  labels:
    app: refuel-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refuel-web-app
  template:
    metadata:
      labels:
        app: refuel-web-app
    spec:
      containers:
      - name: refuel-web-app
        image: timebertt/refuel-web-app
        env:
        - name: MYSQL_HOST
          value: "my-app-mysql-service.default.svc"
        - name: SERVER_HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 5555

---
#Begin: Service
kind: Service
apiVersion: v1
metadata:
  name: refuel-web-app-service
spec:
  selector:
    app: refuel-web-app
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
#End: Service

---
#Begin: Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: refuel-web-app-ingress
  annotations:
    cert.gardener.cloud/purpose: managed
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: refuel-web-app-service
            port:
              number: 5555
    # remove when running on local cluster (e.g. minikube) or adapt to ingress domain
    host: app.ingress.big-data-labs.adm2021.shoot.canary.k8s-hana.ondemand.com
