apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  labels:
    app: memcached
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached:alpine
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: my-memcached-service
spec:
  # Headless service (i.e., no ip is assigned)
  clusterIP: None
  selector:
    app: my-memcached
  ports:
  - port: 11211
    targetPort: 11211
