apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysecretpw"
        - name: MYSQL_DATABASE
          value: "prices"
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 33060
          name: mysql-xproto
        volumeMounts:
        - name: init-volume
          mountPath: /docker-entrypoint-initdb.d/
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: init-volume
        configMap:
          name: mysql-init
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: mysql
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: mysql
  - name: mysql-xproto
    protocol: TCP
    port: 33060
    targetPort: mysql-xproto
