apiVersion: apps/v1
kind: Deployment
metadata:
  name: refuel-spark-app
  labels:
    app: refuel-spark-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: refuel-spark-app
  template:
    metadata:
      labels:
        app: refuel-spark-app
    spec:
#      serviceAccountName: spark-app # needed when submitting jobs to kubernetes
      containers:
      - name: refuel-spark-app
        image: timebertt/refuel-spark-app
        args:
        - --conf
        - spark.executor.cores=2
        - --conf
        - spark.executor.memory=4000m
        - /app/spark-app.py
        env:
        - name: HADOOP_CONF_DIR
          value: "/hadoop-config"
        - name: HADOOP_USER_NAME
          value: "root"
        - name: HADOOP_JAAS_DEBUG
          value: "true"
        - name: MODE
          value: "cluster"
#        - name: MASTER
#          value: "local"
        - name: MASTER
          value: "yarn"
#        - name: MASTER
#          value: "k8s://https://kubernetes.default:443"
        - name: DEPLOY_MODE
          value: "client"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: hadoop-conf
          mountPath: /hadoop-config
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
