apiVersion: apps/v1
kind: Deployment
metadata:
  name: refuel-web-app
  labels:
    app: refuel-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refuel-web-app
  template:
    metadata:
      labels:
        app: refuel-web-app
    spec:
      containers:
      - name: refuel-web-app
        image: timebertt/refuel-web-app
        readinessProbe:
          httpGet:
            port: 5555
            path: /
            scheme: HTTP
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: SERVER_HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 5555
          name: http
---
kind: Service
apiVersion: v1
metadata:
  name: refuel-web-app
spec:
  selector:
    app: refuel-web-app
  ports:
    - protocol: TCP
      name: http
      port: 5555
      targetPort: 5555
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: refuel-web-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: refuel-web-app
            port:
              name: http
